/* Knowledge base + system prompt for the Aura assistant (server-side, LLM grounding).
   Mirrors knowledge-base.md. Prices are 2026 illustrative snapshots. No backticks in KB text. */

const KB = [
  "# IBERDROLA ESPAÑA — BASE DE CONOCIMIENTO (snapshots 2026, orientativos)",
  "",
  "## Segmentos",
  "Hogares (/hogar), Negocios (autónomos y pymes, /negocios), Comunidades de vecinos (/comunidades), Grandes Clientes/Empresas (/empresas). Transversales: Smart Solar, Nube Solar (Solar Cloud), Movilidad eléctrica (VE), app Mi Iberdrola, Tarjeta Iberdrola.",
  "",
  "## Hogares — Luz",
  "- Plan Estable: precio del kWh FIJO garantizado hasta 5 años. Perfil medio ~67 EUR/mes. 100% renovable.",
  "- Plan Online: precio fijo 24h, 100% online. Perfil medio ~62 EUR/mes. Incluye ventaja de recarga del coche eléctrico (hasta -40% en saldo Mi Iberdrola). Sin permanencia (<=10 kW).",
  "- Plan Online 3 Periodos (discriminación horaria): Punta ~0,194 / Llano ~0,136 / Valle ~0,09999 EUR/kWh. Horas valle 00-08h, fines de semana y festivos. Ideal si puedes mover el consumo a la noche.",
  "- Toda la energía es 100% renovable con garantía de origen.",
  "",
  "## Hogares — Gas (Plan Gas Hogar)",
  "- Precio fijo, 12 meses bloqueado, sin permanencia, hasta 50.000 kWh/año.",
  "- RL.1 (cocina + agua caliente): ~0,0957 EUR/kWh + término fijo ~6,25 EUR/mes.",
  "- RL.2 (con calefacción de gas): ~0,0910 EUR/kWh + término fijo ~11,18 EUR/mes.",
  "- Media ~48,57 EUR/mes para ~4.000 kWh/año (varía mucho invierno/verano).",
  "",
  "## Hogares — Solar / autoconsumo",
  "- Plan Ahorro Solar / Plan Solar: compensa excedentes ~0,04-0,06 EUR/kWh.",
  "- Nube Solar (batería virtual): guarda el VALOR ECONÓMICO (no kWh) de tus excedentes en un monedero y lo descuenta de facturas futuras, incluso de otra vivienda del mismo titular. Es gratis y se activa automáticamente con las tarifas de autoconsumo. Tope ~1.000 EUR/mes; validez hasta 24 meses.",
  "- Smart Solar: instalación llave en mano (estudio, paneles, permisos, dimensionado a medida, financiación 3-10 años y tramitación de subvenciones).",
  "- Smart Solar Pack Premium (dic 2024): microinversores Enphase + módulos AIKO, garantías 25 años.",
  "",
  "## Hogares — Servicios del hogar",
  "- Protección Eléctrica Hogar Plus: urgencias eléctricas <3h hasta 550 EUR/año, electrodomésticos hasta 300 EUR, 1 visita manitas/año. ~10,83 EUR/mes (imp. incl.). Abierta a cualquier hogar.",
  "- Pack Iberdrola Hogar: ~10,83 EUR/mes, 50% dto. los 3 primeros meses. Urgencias + electrodomésticos + protección de pagos + Asistente Smart.",
  "- Urgencias Eléctricas: 3,95 EUR/mes, asistencia <3h.",
  "",
  "## Hogares — Movilidad eléctrica",
  "- Plan Recarga: 2,99 EUR/mes, ~10% dto. en recarga pública.",
  "- Plan Recarga+: 9,99 EUR/mes, ~20% dto. (p. ej. 0,48 vs 0,60 EUR/kWh en 60-200 kW).",
  "- App Movilidad Iberdrola: +11.000 puntos públicos, reserva de cargador, seguimiento en tiempo real y hasta 20% del gasto devuelto en créditos.",
  "- Con Plan Online: recarga en casa y ahorra hasta -40% en tu saldo Mi Iberdrola.",
  "",
  "## Negocios (autónomos y pymes)",
  "- Estructura por potencia: 2.0TD (<15 kW) y 3.0TD (>15 kW).",
  "- Tres formas de tarifa: Plan Estable (plano 24h), Plan Noche (más barato de noche), Plan Comercio (más barato en horario comercial).",
  "- Precio garantizado 5 años, sin permanencia.",
  "- Servicios: Urgencias Eléctricas Negocios 6,95 EUR/mes; Asistencia Eléctrica Negocios 3,95 EUR/mes; Asistente Smart Empresas 2,95 EUR/mes; Asistencia Informática Negocios 2,95 EUR/mes; Protección de Pagos Autónomos 3,95 EUR/mes (con MetLife, cobertura hasta 4.000 EUR).",
  "- Solar: Smart Solar llave en mano. VE: Smart Charging para negocios.",
  "- Idea clave: casar la forma de tarifa con el horario real del negocio (restaurante nocturno -> Plan Noche; comercio diurno -> Plan Comercio + Smart Solar).",
  "",
  "## Comunidades de vecinos",
  "- Smart Solar para comunidades: autoconsumo colectivo llave en mano, con gestión de subvenciones incluida y reparto del ahorro entre vecinos.",
  "- Movilidad compartida: puntos de recarga en el garaje común.",
  "- Comparte Nube Solar y compensación de excedentes.",
  "- Decisión: administrador de fincas + presidente + voto de la junta.",
  "",
  "## Grandes Clientes / Empresas",
  "- PPAs renovables a largo plazo: 100% renovable a precio estable a 10+ años; palanca de electrificación y objetivos RE100 / Scope 2. Iberdrola es nº1 europeo en venta de PPA a largo plazo. Ejemplo Mercadona: >300 MW eólica+solar, ~10 años.",
  "- Infraestructura de recarga a gran escala: suministro, instalación y operación (caso Mercadona: hasta 3.500 puntos en 800 tiendas ES+PT).",
  "- Clientes: Mercadona, Microsoft, Amazon, Apple, Telefónica, Renfe, Gestamp.",
  "- Modelo: Key Account Manager dedicado + revisiones trimestrales (QBR) + reporting ESG.",
  "",
  "## Transversales",
  "- Mi Iberdrola (app): facturas, consumo en tiempo real, gestión de planes, saldo/Nube Solar, descuentos.",
  "- Tarjeta Iberdrola: acumula saldo en Mi Iberdrola y ahorra en la factura de luz.",
  "",
  "## FAQs",
  "- Contratar/cambiarse: necesitas DNI, CUPS (viene en tu factura) y cuenta bancaria. Iberdrola tramita el cambio con tu compañía anterior, sin cortes de suministro. Activación ~5-7 días; efectivo ~1-2 semanas. 100% online.",
  "- Permanencia: potencia <=10 kW sin permanencia; >10 kW 12 meses. Negocios: precio 5 años, sin permanencia.",
  "- Energía verde: sí, 100% renovable con garantía de origen.",
  "- Nube Solar: batería virtual que guarda el valor en EUR de los excedentes para descontarlo de facturas.",
  "- Excedentes solares: compensación ~0,04-0,06 EUR/kWh; lo no compensado va a la Nube Solar.",
  "- Precio de la luz hoy: en iberdrola.es y en la app Mi Iberdrola.",
  "- Baja de un servicio: desde Mi Iberdrola o atención al cliente 900 225 235.",
  "- Atención al cliente: 900 225 235 · clientes@tuiberdrola.es · WhatsApp · Mi Iberdrola.",
  "",
  "## Glosario",
  "- CUPS: Código Universal del Punto de Suministro (identifica tu punto de luz/gas).",
  "- 2.0TD: peaje para potencia <=15 kW. 3.0TD: peaje para >15 kW.",
  "- Punta/Llano/Valle: periodos horarios de precio (caro/medio/barato).",
  "- Discriminación horaria: pagar distinto según la hora.",
  "- PPA: contrato de compra de energía renovable a largo plazo.",
  "- Autoconsumo: generar tu propia energía (p. ej. con placas solares)."
].join("\n");

const SYSTEM_BASE = [
  "Eres Aura, la asistente virtual de Iberdrola España. Ayudas a clientes y visitantes a entender los productos y servicios de Iberdrola y les propones ideas relevantes.",
  "Reglas de contenido:",
  "- Responde SIEMPRE en español, con tono cálido, claro y cercano (tuteo).",
  "- Básate ÚNICAMENTE en la BASE DE CONOCIMIENTO proporcionada. Si algo no está en ella, dilo con honestidad y ofrece el 900 225 235 o la app Mi Iberdrola. No inventes datos, precios ni condiciones.",
  "- Sé concisa: 2-6 frases o una lista corta.",
  "- Cuando encaje, propón proactivamente un producto/servicio o un siguiente paso útil.",
  "- Los precios son orientativos (snapshots 2026) y pueden variar; indícalo si das cifras.",
  "- No pidas ni manejes datos personales sensibles; para gestiones de cuenta, dirige a Mi Iberdrola o al 900 225 235.",
  "",
  "Reglas de FORMATO (MUY IMPORTANTE):",
  "- Responde SIEMPRE en HTML válido, NUNCA en Markdown. Prohibido usar *, **, #, backticks, guiones para listas o cualquier sintaxis Markdown.",
  "- Devuelve solo el fragmento HTML del cuerpo (sin <html>, <head>, <body>, <script>, <style> ni atributos style=).",
  "- Usa <p> para párrafos, <strong> para lo importante, <ul>/<li> u <ol>/<li> para listas, <br> para saltos puntuales.",
  "- Cuando compares planes, precios u opciones, usa una <table> con <thead> y <tbody> (encabezados <th>, celdas <td>). Mantén las tablas compactas (2-4 columnas).",
  "- Para enlaces usa <a href=\"...\">. Rutas internas útiles: /hogar, /negocios, /comunidades, /empresas.",
  "- Incluye <img src=\"URL\" alt=\"...\"> SOLO si tienes la certeza de una URL pública real y válida; si no la tienes, NO pongas imágenes (nunca inventes URLs).",
  "- Puedes usar emojis con moderación. No uses encabezados <h1>/<h2>; si necesitas un subtítulo usa <strong> o <h4>."
].join("\n");

module.exports = { KB, SYSTEM_BASE };
